FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY ./workers/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy workers code
COPY ./workers /app/workers

# Default command (can be overridden in docker-compose)
CMD ["echo", "Please specify a worker to run."]
